[package]
name = "rust_astrofloat"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = ">= 1.0.95"
num-traits = ">= 0.2.19"
# once_cell = ">= 1.20.2"
astro-float = ">= 0.9.4"
num-bigint = ">= 0.4.6"
