[package]
name = "rust_astrofloat"
version = "0.1.0"
edition = "2024"

[profile.release]
panic = 'abort'
codegen-units = 1
lto = 'fat'
strip = true

[dependencies]
anyhow = ">= 1.0.95"
astro-float = ">= 0.9.4"
